from app.views.customer_club_mainpage import CustomerClubMainPage
from app.views.customer_homepage import CustomerHomePage
from app.views.customer_view_res import CustomerViewReservations
from app.views.login_view import LoginView
from app.views.reservation_details_page import ReservationDetailsPage
from app.views.mod_res_page import ModifyReservationPage
from app.views.msg_popup import MessagePopup
from app.views.cancel_res_dialog import CancelReservationDialog
from app.views.qrcode_dialog import QRCodeDialog
from app.views.staff_home_page import StaffHomePage
from app.views.review_page import ReviewPage
from app.views.event_form import EventForm
from app.views.add_event_view import AddEventPage